const universitiesByCountry = {
  'Algeria': [
    'University of Algiers',
    'University of Oran',
    'University of Constantine',
    'University of Science and Technology Houari Boumediene',
    'University of Tlemcen',
    'University of Annaba',
    'University of Setif',
    'University of Blida',
    'University of Batna',
    'University of Bejaia',
    'University of Biskra',
    'University of Djelfa',
    'University of El Oued',
    'University of Guelma',
    'University of Jijel',
    'University of Khenchela',
    'University of Laghouat',
    'University of Mascara',
    'University of Medea',
    'University of Mila',
    'University of Mostaganem',
    'University of Msila',
    'University of Ouargla',
    'University of Saida',
    'University of Skikda',
    'University of Souk Ahras',
    'University of Tabia',
    'University of Tebessa',
    'University of Tiaret',
    'University of Tizi Ouzou',
    'University of Adrar',
    'University of Boumerdes',
    'University of Chlef',
    'University of Tissemsilt',
    'University of Ain Temouchent',
    'University of Naama',
    'University of Oum El Bouaghi',
    'University of Illizi',
    'University of Tindouf',
    'Algerian Business School',
    'National Polytechnic School',
    'National School of Computer Science',
    'National School of Engineering',
  ],
  'Angola': [
    'University Agostinho Neto',
    'Catholic University of Angola',
    'Independent University of Angola',
    'University of Lusíada',
    'Jean Piaget University of Angola',
    'University of Benguela',
    'University of José Eduardo dos Santos',
    'University of Huambo',
    'University of Namibe',
    'Mandume Ya Ndemufayo University',
    'Technical University of Angola',
    'Universidade Gregório Semedo',
    'Universidade Óscar Ribas',
    'Universidade Metodista de Angola',
    'Universidade de Belas',
  ],
  'Benin': [
    'University of Abomey-Calavi',
    'University of Parakou',
    'Catholic University of Benin',
    'Catholic University of West Africa',
    'University of Science and Technology of Benin',
    'African University of Technology and Management',
    'University of Applied Sciences',
    'Houdegbe North American University Benin',
    'International University of Benin',
    'University of Porto-Novo',
  ],
  'Botswana': [
    'University of Botswana',
    'Botswana International University of Science and Technology',
    'Botho University',
    'Ba Isago University',
    'Limkokwing University of Creative Technology',
    'ABM University College',
    'Gaborone University College of Law and Professional Studies',
  ],
  'Burkina Faso': [
    'University of Ouagadougou',
    'University of Bobo-Dioulasso',
    'University of Koudougou',
    'Catholic University of West Africa',
    'International University of Ouagadougou',
    'University of Fada N\'Gourma',
    'University of Ouahigouya',
    'University of Dedougou',
    'University of Ziniaré',
    'Thomas Sankara University',
    'Norbert Zongo University',
    'University of Banfora',
  ],
  'Burundi': [
    'University of Burundi',
    'University of Ngozi',
    'Hope Africa University',
    'International Leadership University',
    'Bujumbura International University',
    'Light University of Bujumbura',
    'Great Lakes University',
    'University of Mwaro',
    'University of Gitega',
    'Saint John of God University',
    'Martin Luther King University',
  ],
  'Cameroon': [
    'University of Yaounde I',
    'University of Yaounde II',
    'University of Douala',
    'University of Buea',
    'University of Dschang',
    'University of Maroua',
    'University of Ngaoundere',
    'University of Bamenda',
    'University of Ebolowa',
    'University of Bertoua',
    'University of Garoua',
    'Catholic University of Cameroon',
    'Catholic University of Central Africa',
    'University of Buea',
    'Fomic Polytechnic',
    'ICT University',
    'St. Monica University',
    'Bamenda University of Science and Technology',
    'University of the Mountains',
  ],
  'Cape Verde': [
    'University of Cape Verde',
    'Jean Piaget University of Cape Verde',
    'University of Mindelo',
    'Atlantic University',
    'University of Santiago',
    'Institute of Education at a Distance',
  ],
  'Central African Republic': [
    'University of Bangui',
    'Eugene Jamot University',
    'University of Mbaiki',
  ],
  'Chad': [
    'University of N\'Djamena',
    'University of Moundou',
    'University of Sarh',
    'University of Abéché',
    'University of Fachi',
    'American University of Chad',
    'King Faisal University of Chad',
    'Catholic University of West Africa',
  ],
  'Comoros': [
    'University of Comoros',
    'Higher Institute of Technology',
  ],
  'Congo': [
    'Marien Ngouabi University',
    'University of Brazzaville',
    'Denis Sassou N\'Guesso University',
    'University of Oyo',
    'Higher Institute of Management',
    'Teacher Training College of Congo',
  ],
  'Democratic Republic of the Congo': [
    'University of Kinshasa',
    'University of Lubumbashi',
    'University of Kisangani',
    'Catholic University of Congo',
    'University of Goma',
    'University of Bukavu',
    'University of Mbujimayi',
    'University of Bandundu',
    'University of Kalemie',
    'University of Kananga',
    'University of Kolwezi',
    'University of Kikwit',
    'University of Mbandaka',
    'University of Tshikapa',
    'University of Boma',
    'University of Matadi',
    'University of Inongo',
    'University of Kindu',
    'University of Bunia',
    'University of Kenge',
    'University of Isiro',
    'Protestant University in Congo',
    'National Pedagogical University',
    'Open Christian University',
    'Adventist University of Goma',
    'William Booth University',
    'University of North Kivu',
    'University of Uele',
    'University of Kamina',
    'Simon Kimbangu University',
  ],
  'Djibouti': [
    'University of Djibouti',
    'Higher Institute of Technology',
  ],
  'Egypt': [
    'Cairo University',
    'Alexandria University',
    'Ain Shams University',
    'Al-Azhar University',
    'American University in Cairo',
    'German University in Cairo',
    'Helwan University',
    'Mansoura University',
    'Zagazig University',
    'Assiut University',
    'Tanta University',
    'University of Suez Canal',
    'Minia University',
    'Minufiya University',
    'Beni Suef University',
    'Sohag University',
    'South Valley University',
    'Fayoum University',
    'Benha University',
    'Kafrelsheikh University',
    'Suez University',
    'Damietta University',
    'Port Said University',
    'Luxor University',
    'Arish University',
    'Damanhour University',
    'New Valley University',
    'Sadat City University',
    'Matrouh University',
    'Cairo Higher Institute',
    'Modern Sciences and Arts University',
    'Misr International University',
    'Misr University for Science and Technology',
    'Arab Academy for Science and Technology and Maritime Transport',
    'Nile University',
    'British University in Egypt',
    'Cairo American University',
    'Canadian International College',
    'Ahram Canadian University',
    'October University for Modern Sciences and Arts',
    'Pharos University in Alexandria',
    'Future University in Egypt',
    'University of Hertfordshire in Egypt',
  ],
  'Equatorial Guinea': [
    'National University of Equatorial Guinea',
    'University of Equatorial Guinea',
  ],
  'Eritrea': [
    'University of Asmara',
    'Eritrea Institute of Technology',
    'Orotta School of Medicine',
    'College of Marine Science and Technology',
    'Hamelmalo Agricultural College',
  ],
  'Eswatini': [
    'University of Eswatini',
    'Southern African Nazarene University',
    'Eswatini Medical Christian University',
  ],
  'Ethiopia': [
    'Addis Ababa University',
    'Bahir Dar University',
    'Jimma University',
    'Mekelle University',
    'University of Gondar',
    'Hawassa University',
    'Arba Minch University',
    'Haramaya University',
    'Adama Science and Technology University',
    'Debre Berhan University',
    'Debre Markos University',
    'Wolaita Sodo University',
    'Wollo University',
    'Semera University',
    'Dire Dawa University',
    'Jigjiga University',
    'University of Axum',
    'Bule Hora University',
    'Dilla University',
    'Kotebe Metropolitan University',
    'Madawalabu University',
    'Mizan Tepi University',
    'Ambo University',
    'Wollegi University',
    'Assosa University',
    'Bonga University',
    'Ethiopian Civil Service University',
    'Mettu University',
    'Raya University',
    'Addis Ababa Science and Technology University',
    'Adigrat University',
    'Oda Bultum University',
    'Unity University',
    'St. Mary\'s University',
    'Rift Valley University',
  ],
  'Gabon': [
    'University of Omar Bongo',
    'University of Sciences and Techniques of Masuku',
    'University of Health Sciences Libreville',
    'University of Libreville',
    'Catholic University of Central Africa',
    'African University of Science and Technology',
    'Pan-African University',
  ],
  'Gambia': [
    'University of the Gambia',
    'American International University West Africa',
    'MDI Management Development Institute',
  ],
  'Ghana': [
    'University of Ghana',
    'Kwame Nkrumah University of Science and Technology',
    'University of Cape Coast',
    'University of Education, Winneba',
    'University for Development Studies',
    'University of Professional Studies',
    'University of Mines and Technology',
    'University of Health and Allied Sciences',
    'University of Energy and Natural Resources',
    'University of Environment and Sustainable Development',
    'Ghana Institute of Management and Public Administration',
    'Ghana Communication Technology University',
    'Accra Technical University',
    'Kumasi Technical University',
    'Cape Coast Technical University',
    'Koforidua Technical University',
    'Tamale Technical University',
    'Bolgatanga Technical University',
    'Takoradi Technical University',
    'Sunyani Technical University',
    'Ho Technical University',
    'Wa Technical University',
    'Ashesi University',
    'Central University',
    'Valley View University',
    'All Nations University',
    'Pentecost University',
    'Presbyterian University College',
    'Catholic University College of Ghana',
    'Christian Service University College',
    'Methodist University Ghana',
    'Wisconsin International University College',
    'Regent University College of Science and Technology',
    'Regional Maritime University',
    'Garden City University College',
    'African University College of Communications',
    'Zenith University College',
    'DataLink University College',
    'Ensign Global College',
    'Knutsford University College',
    'Lancaster University Ghana',
    'Webster University Ghana Campus',
  ],
  'Guinea': [
    'University of Conakry',
    'University of N\'Zérékoré',
    'University of Kankan',
    'University of Labé',
    'Gamal Abdel Nasser University of Conakry',
    'General Lansana Conté University',
    'International University of Grand-Bassam',
    'Kofi Annan University of Guinea',
  ],
  'Guinea-Bissau': [
    'University of Bissau',
    'Amílcar Cabral University',
    'Institute of Applied Sciences and Technology',
  ],
  "Côte d'Ivoire": [
    'University of Cocody',
    'University of Abobo-Adjamé',
    'University of Bouaké',
    'University of Korhogo',
    'University of Daloa',
    'University of San Pedro',
    'University of Man',
    'Catholic University of West Africa',
    'International University of Grand-Bassam',
    'National Polytechnic Institute of Houphouët-Boigny',
    'Higher Institute of Management',
    'Pigier-CI Business School',
  ],
  'Kenya': [
    'University of Nairobi',
    'Kenyatta University',
    'Moi University',
    'Egerton University',
    'Jomo Kenyatta University of Agriculture and Technology',
    'Maseno University',
    'University of Eldoret',
    'Technical University of Kenya',
    'Technical University of Mombasa',
    'Dedan Kimathi University of Technology',
    'University of Kabianga',
    'Karatina University',
    'Laikipia University',
    'Masinde Muliro University of Science and Technology',
    'Meru University of Science and Technology',
    'Multimedia University of Kenya',
    'Pwani University',
    'Rongo University',
    'University of Embu',
    'South Eastern Kenya University',
    'Chuka University',
    'Machakos University',
    'Maasai Mara University',
    'Murang\'a University of Technology',
    'Kibabii University',
    'University of Nairobi Central',
    'Strathmore University',
    'United States International University Africa',
    'Daystar University',
    'Catholic University of Eastern Africa',
    'Mount Kenya University',
    'Africa Nazarene University',
    'St. Paul\'s University',
    'Kabarak University',
    'Scott Christian University',
    'University of Eastern Africa, Baraton',
    'Pan Africa Christian University',
    'Management University of Africa',
    'Adventist University of Africa',
    'KCA University',
    'Africa International University',
    'Riara University',
    'Zetech University',
    'Presbyterian University of East Africa',
    'Cooperative University of Kenya',
    'Alupe University',
    'University of Kigali',
    'Tharaka University',
  ],
  'Lesotho': [
    'National University of Lesotho',
    'Botho University',
    'Limkokwing University of Creative Technology',
  ],
  'Liberia': [
    'University of Liberia',
    'Stella Maris Polytechnic',
    'Cuttington University',
    'African Methodist Episcopal University',
    'United Methodist University',
    'Starz University',
    'Adventist University of West Africa',
  ],
  'Libya': [
    'University of Tripoli',
    'University of Benghazi',
    'University of Misurata',
    'University of Sabha',
    'University of Zawia',
    'University of Derna',
    'University of Tobruk',
    'University of Omar Al-Mukhtar',
    'University of Sebha',
    'University of Gharyan',
    'University of Sirte',
    'University of Elmergib',
    'University of Bani Walid',
    'University of Zintan',
    'Asmarya University',
    'University of Ajdabiya',
    'Libyan International Medical University',
    'Aljabal Algharbi University',
    'University of Nalut',
    'Tripoli University of Technology',
  ],
  'Madagascar': [
    'University of Antananarivo',
    'University of Mahajanga',
    'University of Fianarantsoa',
    'University of Toamasina',
    'University of Toliara',
    'University of Antsiranana',
    'Higher Institute of Technology Antananarivo',
    'Catholic University of Madagascar',
  ],
  'Malawi': [
    'University of Malawi',
    'Mzuzu University',
    'Malawi University of Science and Technology',
    'Malawi University of Business and Applied Sciences',
    'Lilongwe University of Agriculture and Natural Resources',
    'Catholic University of Malawi',
    'African Bible College',
    'University of Livingstonia',
    'DMI St John the Baptist University',
  ],
  'Mali': [
    'University of Bamako',
    'University of Sciences, Techniques and Technologies of Bamako',
    'University of Tombouctou',
    'University of Segou',
    'University of Koulikoro',
    'Catholic University of West Africa',
  ],
  'Mauritania': [
    'University of Nouakchott',
    'University of Sciences and Technology of Mauritania',
    'Higher Institute of Technological Education',
    'National University of Mauritania',
  ],
  'Mauritius': [
    'University of Mauritius',
    'University of Technology, Mauritius',
    'University of Mascareignes',
    'Mauritius Institute of Education',
    'African Leadership University',
    'Open University of Mauritius',
    'Charles Telfair Institute',
    'Middlesex University Mauritius',
    'Curtin University Mauritius',
    'University of Liverpool Mauritius',
  ],
  'Morocco': [
    'University of Mohammed V',
    'University of Hassan II',
    'University of Al Quaraouiyine',
    'University of Ibn Zohr',
    'University of Hassan I',
    'University of Sidi Mohamed Ben Abdellah',
    'University of Chouaib Doukkali',
    'University of Moulay Ismail',
    'University of Ibn Tofail',
    'University of Abdelmalek Essaadi',
    'University of Cadi Ayyad',
    'University of Hassan II Mohammedia',
    'International University of Rabat',
    'Al Akhawayn University',
    'University of Mundiapolis',
    'University of Mohammed VI Polytechnic',
    'University of L\'Hassania',
    'University of Euromed',
    'School of Information Sciences',
    'Higher Institute of Management and Information Technology',
  ],
  'Mozambique': [
    'University of Eduardo Mondlane',
    'Catholic University of Mozambique',
    'Pedagogical University of Maputo',
    'University of São Tomás de Moçambique',
    'University of Lúrio',
    'University of Zambeze',
    'Save University',
    'Higher Institute of Science and Technology of Mozambique',
    'Higher Institute of International Relations',
    'Institute of Transport and Communications',
    'University of Nachingwea',
    'Maputo University',
    'Polytechnic University of Mozambique',
    'University of Mozambique',
  ],
  'Namibia': [
    'University of Namibia',
    'Namibia University of Science and Technology',
    'International University of Management',
    'University of the People',
  ],
  'Niger': [
    'Abdou Moumouni University',
    'University of Maradi',
    'University of Tahoua',
    'University of Zinder',
    'University of Agadez',
    'University of Tillaberi',
    'University of Diffa',
    'African University of Technology and Management',
    'Higher Institute of Mining, Industry and Geology',
  ],
  'Rwanda': [
    'University of Rwanda',
    'University of Kigali',
    'Adventist University of Central Africa',
    'Catholic University of Rwanda',
    'University of Gitwe',
    'University of Technology and Arts of Byumba',
    'University of Kibungo',
    'Mount Kenya University Rwanda',
    'Carnegie Mellon University Africa',
    'Davis College',
    'Akilah Institute',
    'University of Lay Adventists of Kigali',
    'INILAK Business School',
    'Institute of Legal Practice and Development',
  ],
  'São Tomé and Príncipe': [
    'University of São Tomé and Príncipe',
    'National Institute of Education and Professional Development',
  ],
  'Senegal': [
    'Cheikh Anta Diop University',
    'University of Gaston Berger',
    'University of Thiès',
    'University of Ziguinchor',
    'University of Bambey',
    'University of Assane Seck',
    'University of Alioune Diop',
    'University of Sine Saloum El Hadji Ibrahima Niasse',
    'University of Amadou Mahtar Mbow',
    'African University of Technology and Management',
    'Catholic University of West Africa',
    'Higher Institute of Management',
    'Bordeaux Senegalese University',
  ],
  'Seychelles': [
    'University of Seychelles',
    'Guy Morel Institute',
  ],
  'Sierra Leone': [
    'University of Sierra Leone',
    'Njala University',
    'Fourah Bay College',
    'Ernest Bai Koroma University of Science and Technology',
    'University of Makeni',
    'Central University of Sierra Leone',
  ],
  'Somalia': [
    'Somali National University',
    'Mogadishu University',
    'University of Hargeisa',
    'East Africa University',
    'University of Burao',
    'University of Somalia',
    'Plasma University',
    'Admas University',
    'Gollis University',
    'Hormuud University',
    'Amoud University',
    'University of Bosaso',
    'University of Gedo',
    'Kismayo University',
    'Puntland State University',
    'Maakhir University',
  ],
  'South Africa': [
    'University of Cape Town',
    'University of the Witwatersrand',
    'University of Pretoria',
    'Stellenbosch University',
    'University of Johannesburg',
    'University of KwaZulu-Natal',
    'University of the Western Cape',
    'Rhodes University',
    'University of the Free State',
    'University of Fort Hare',
    'North-West University',
    'University of Limpopo',
    'University of Zululand',
    'University of Venda',
    'University of Mpumalanga',
    'Sol Plaatje University',
    'Walter Sisulu University',
    'Nelson Mandela University',
    'Cape Peninsula University of Technology',
    'Durban University of Technology',
    'Mangosuthu University of Technology',
    'Central University of Technology',
    'Tshwane University of Technology',
    'Vaal University of Technology',
    'University of South Africa',
    'Sefako Makgatho Health Sciences University',
    'Monash South Africa',
    'University of the Witwatersrand Johannesburg',
    'IIE Varsity College',
    'St Augustine College of South Africa',
    'Cornerstone Institute',
    'University of the People South Africa',
  ],
  'South Sudan': [
    'University of Juba',
    'University of Bahr El-Ghazal',
    'Upper Nile University',
    'University of Northern Bahr el Ghazal',
    'John Garang Memorial University',
    'University of Rumbek',
    'University of Jonglei',
    'Dr. John Garang Memorial University',
  ],
  'Sudan': [
    'University of Khartoum',
    'University of Gezira',
    'University of Sudan',
    'University of Medical Sciences and Technology',
    'University of Khartoum College',
    'University of Bahri',
    'University of Nyala',
    'University of Kassala',
    'University of Dongola',
    'University of Kordofan',
    'University of Gadarif',
    'University of Simar',
    'University of Holy Quran and Islamic Sciences',
    'University of Al-Fashir',
    'University of West Kordofan',
    'University of Mavi',
    'University of Zalingei',
    'University of Shendi',
    'University of El Imam El Mahdi',
    'University of Red Sea',
    'University of Dongola',
    'University of Albutana',
    'University of Kassala',
    'University of Sinnar',
    'University of El Obeid',
    'University of Al Fajr',
    'Sudan University of Science and Technology',
    'University of Medical Sciences and Technology',
    'Ahfad University for Women',
    'Future University of Sudan',
    'International University of Africa',
    'Neelain University',
    'Omdurman Islamic University',
    'University of Science and Technology',
    'Al-Zaiem Al-Azhari University',
    'Bayadir University',
    'Canadian University of Sudan',
  ],
  'Tanzania': [
    'University of Dar es Salaam',
    'University of Dar es Salaam College',
    'University of Dar es Salaam Mbeya College',
    'Sokoine University of Agriculture',
    'Muhimbili University of Health and Allied Sciences',
    'Open University of Tanzania',
    'University of Dodoma',
    'Nelson Mandela African Institute of Science and Technology',
    'St. John\'s University of Tanzania',
    'Zanzibar University',
    'Hubert Kairuki Memorial University',
    'Tumaini University Makumira',
    'St. Augustine University of Tanzania',
    'International Medical and Technological University',
    'University of Arusha',
    'Mount Meru University',
    'Ruaha Catholic University',
    'Teofilo Kisanji University',
    'Sebatian Kolowa Memorial University',
    'Mwenge Catholic University',
    'University of Iringa',
    'Jordan University College',
    'Muslim University of Morogoro',
    'College of Business Education',
    'Institute of Accountancy Arusha',
  ],
  'Togo': [
    'University of Lomé',
    'University of Kara',
    'Catholic University of West Africa',
    'African Technology and Management University',
    'Higher Institute of Management',
  ],
  'Tunisia': [
    'University of Tunis',
    'University of Tunis El Manar',
    'University of Carthage',
    'University of Manouba',
    'University of Sfax',
    'University of Sousse',
    'University of Monastir',
    'University of Gabes',
    'University of Gafsa',
    'University of Kairouan',
    'University of Jendouba',
    'University of Thala',
    'University of Kasserine',
    'Mediterranean School of Business',
    'University of Central Tunisia',
    'Carthage Business School',
    'Higher Institute of Technological Studies',
    'National Institute of Applied Science and Technology',
  ],
  'Uganda': [
    'Makerere University',
    'Kampala International University',
    'Islamic University in Uganda',
    'Uganda Martyrs University',
    'Nkumba University',
    'Gulu University',
    'Mbarara University of Science and Technology',
    'Kyambogo University',
    'Busitema University',
    'Uganda Christian University',
    'Mountains of the Moon University',
    'Kabale University',
    'Muni University',
    'Lira University',
    'Soroti University',
    'Bugema University',
    'Uganda Technology and Management University',
    'Kumi University',
    'Victoria University Uganda',
    'International University of East Africa',
    'St. Lawrence University',
    'LivingStone International University',
    'Bishop Stuart University',
    'University of Kisubi',
    'African Rural University',
    'University of the Sacred Heart Gulu',
  ],
  'Zambia': [
    'University of Zambia',
    'Copperbelt University',
    'Mulungushi University',
    'University of Lusaka',
    'University of Ndola',
    'University of Kabwe',
    'University of Africa',
    'Chalimbana University',
    'Muslim University College',
    'University of the People Zambia',
    'Evelyn Hone College of Applied Arts and Commerce',
    'National Institute of Public Administration',
    'DMI St. Eugene University',
  ],
  'Zimbabwe': [
    'University of Zimbabwe',
    'National University of Science and Technology',
    'Midlands State University',
    'Great Zimbabwe University',
    'Bindura University of Science Education',
    'Chinhoyi University of Technology',
    'Lupane State University',
    'Harare Institute of Technology',
    'Manicaland State University of Applied Sciences',
    'Women\'s University in Africa',
    'Africa University',
    'Catholic University of Zimbabwe',
    'Zimbabwe Ezekiel Guti University',
    'Solusi University',
    'University of the People Zimbabwe',
  ],
}

function getUniversitiesForCountry(country) {
  const list = universitiesByCountry[country]
  if (!list) return []
  return list.map(name => ({ name, country, level: 'University' }))
}

function getAllUniversitiesForCountries() {
  const all = []
  for (const [country, list] of Object.entries(universitiesByCountry)) {
    for (const name of list) {
      all.push({ name, country, level: 'University' })
    }
  }
  return all
}

module.exports = { universitiesByCountry, getUniversitiesForCountry, getAllUniversitiesForCountries }
