const waecNigeria = require('./nigeriaSecondaryWAEC')

const schoolsByCountry = {
  'Nigeria': [
    // ================ ABIA ================
    { name: 'Federal Government College, Aba', state: 'Abia' },
    { name: 'Federal Government College, Ohafia', state: 'Abia' },
    { name: 'Federal Science and Technical College, Aba', state: 'Abia' },
    { name: 'Government College, Umuahia', state: 'Abia' },
    { name: 'Abia State Secondary School, Uturu', state: 'Abia' },
    { name: 'Girls High School, Umuahia', state: 'Abia' },
    { name: 'Sacred Heart Secondary School, Aba', state: 'Abia' },
    { name: 'Domus Mariae College, Aba', state: 'Abia' },
    { name: 'Marist Brothers Juniorate, Uturu', state: 'Abia' },
    { name: 'Living Word Academy, Aba', state: 'Abia' },
    { name: 'Nigerian Tulip International College, Aba', state: 'Abia' },
    { name: 'Azikiwe Memorial Secondary School, Aba', state: 'Abia' },

    // ================ ADAMAWA ================
    { name: 'Federal Government College, Yola', state: 'Adamawa' },
    { name: 'Federal Government College, Mubi', state: 'Adamawa' },
    { name: 'Federal Science and Technical College, Yola', state: 'Adamawa' },
    { name: 'Government Secondary School, Yola', state: 'Adamawa' },
    { name: 'Government Girls Secondary School, Yola', state: 'Adamawa' },
    { name: 'Baptist High School, Numan', state: 'Adamawa' },
    { name: 'General Murtala Mohammed College, Yola', state: 'Adamawa' },
    { name: 'Special Science Secondary School, Yola', state: 'Adamawa' },
    { name: 'AUN Academy, Yola', state: 'Adamawa' },
    { name: 'Nigerian Tulip International College, Yola', state: 'Adamawa' },
    { name: 'Modibbo Adama Science Academy, Yola', state: 'Adamawa' },
    { name: 'Heavenly City Academy, Yola', state: 'Adamawa' },

    // ================ AKWA IBOM ================
    { name: 'Federal Government College, Ikot Ekpene', state: 'Akwa Ibom' },
    { name: 'Federal Government Girls College, Afaha Oku', state: 'Akwa Ibom' },
    { name: 'Federal Science and Technical College, Uyo', state: 'Akwa Ibom' },
    { name: 'Government Secondary School, Uyo', state: 'Akwa Ibom' },
    { name: 'Government Technical College, Ikot Osurua', state: 'Akwa Ibom' },
    { name: 'St. Anne\'s Girls Secondary School, Ikot Ekpene', state: 'Akwa Ibom' },
    { name: 'Salvation Army Secondary School, Uyo', state: 'Akwa Ibom' },
    { name: 'Lutheran High School, Uyo', state: 'Akwa Ibom' },
    { name: 'Topfaith International School, Mkpatak', state: 'Akwa Ibom' },
    { name: 'Regent School, Uyo', state: 'Akwa Ibom' },
    { name: 'British International Secondary School, Uyo', state: 'Akwa Ibom' },
    { name: 'Nigerian Tulip International College, Uyo', state: 'Akwa Ibom' },
    { name: 'Holy Fervour Academy, Uyo', state: 'Akwa Ibom' },

    // ================ ANAMBRA ================
    { name: 'Federal Government College, Nise', state: 'Anambra' },
    { name: 'Federal Government Girls College, Onitsha', state: 'Anambra' },
    { name: 'Dennis Memorial Grammar School, Onitsha', state: 'Anambra' },
    { name: 'Christ the King College, Onitsha', state: 'Anambra' },
    { name: 'St. John\'s Secondary School, Awka', state: 'Anambra' },
    { name: 'Queen\'s School, Enugu-Awka', state: 'Anambra' },
    { name: 'Anglican Girls Secondary School, Neni', state: 'Anambra' },
    { name: 'Metropolitan Secondary School, Onitsha', state: 'Anambra' },
    { name: 'Marian College, Awkunanaw', state: 'Anambra' },
    { name: 'Regina Caeli Girls Secondary School, Onitsha', state: 'Anambra' },
    { name: 'Holy Child Secondary School, Onitsha', state: 'Anambra' },
    { name: 'Nigerian Tulip International College, Awka', state: 'Anambra' },
    { name: 'St. Joseph\'s Secondary School, Awka', state: 'Anambra' },

    // ================ BAUCHI ================
    { name: 'Federal Government College, Bauchi', state: 'Bauchi' },
    { name: 'Federal Government College, Azare', state: 'Bauchi' },
    { name: 'Federal Science and Technical College, Bauchi', state: 'Bauchi' },
    { name: 'Government Secondary School, Bauchi', state: 'Bauchi' },
    { name: 'Government Girls College, Bauchi', state: 'Bauchi' },
    { name: 'Command Secondary School, Bauchi', state: 'Bauchi' },
    { name: 'Federal Science College, Bauchi', state: 'Bauchi' },
    { name: 'Nigerian Tulip International College, Bauchi', state: 'Bauchi' },
    { name: 'Al-Mumtaz International School, Bauchi', state: 'Bauchi' },
    { name: 'Summit Academy, Bauchi', state: 'Bauchi' },
    { name: 'Yusuf Tatari Ali Polytechnic Secondary School, Bauchi', state: 'Bauchi' },

    // ================ BAYELSA ================
    { name: 'Federal Government College, Yenagoa', state: 'Bayelsa' },
    { name: 'Federal Government Girls College, Yenagoa', state: 'Bayelsa' },
    { name: 'Government Secondary School, Yenagoa', state: 'Bayelsa' },
    { name: 'Bishop Dimeari Grammar School, Yenagoa', state: 'Bayelsa' },
    { name: 'St. Jude\'s Girls Secondary School, Amassoma', state: 'Bayelsa' },
    { name: 'Community Secondary School, Kaiama', state: 'Bayelsa' },
    { name: 'Government Technical College, Yenogua', state: 'Bayelsa' },
    { name: 'Niger Delta Science School, Yenagoa', state: 'Bayelsa' },
    { name: 'Dominican International School, Yenagoa', state: 'Bayelsa' },
    { name: 'Rainbow Academy, Yenagoa', state: 'Bayelsa' },
    { name: 'Baptist International Academy, Yenagoa', state: 'Bayelsa' },

    // ================ BENUE ================
    { name: 'Federal Government College, Makurdi', state: 'Benue' },
    { name: 'Federal Government College, Otukpo', state: 'Benue' },
    { name: 'Federal Science and Technical College, Otukpo', state: 'Benue' },
    { name: 'Government Secondary School, Makurdi', state: 'Benue' },
    { name: 'St. Francis Secondary School, Makurdi', state: 'Benue' },
    { name: 'Mount Saint Gabriel\'s Secondary School, Makurdi', state: 'Benue' },
    { name: 'Government Girls Secondary School, Makurdi', state: 'Benue' },
    { name: 'Titush Global College, Katsina-Ala', state: 'Benue' },
    { name: 'Salem Academy, Makurdi', state: 'Benue' },
    { name: 'Standard International School, Makurdi', state: 'Benue' },
    { name: 'Hope Academy, Makurdi', state: 'Benue' },
    { name: 'Nigerian Tulip International College, Makurdi', state: 'Benue' },

    // ================ BORNO ================
    { name: 'Federal Government College, Maiduguri', state: 'Borno' },
    { name: 'Federal Government Girls College, Maiduguri', state: 'Borno' },
    { name: 'Federal Science and Technical College, Maiduguri', state: 'Borno' },
    { name: 'Government Secondary School, Maiduguri', state: 'Borno' },
    { name: 'Government College, Maiduguri', state: 'Borno' },
    { name: 'Yerwa Girls Secondary School, Maiduguri', state: 'Borno' },
    { name: 'Borno Girls Secondary School, Maiduguri', state: 'Borno' },
    { name: 'Al-Ansar International School, Maiduguri', state: 'Borno' },
    { name: 'Nigerian Tulip International College, Maiduguri', state: 'Borno' },
    { name: 'Shiloh Academy, Maiduguri', state: 'Borno' },
    { name: 'Command Science Secondary School, Maiduguri', state: 'Borno' },

    // ================ CROSS RIVER ================
    { name: 'Federal Government College, Calabar', state: 'Cross River' },
    { name: 'Federal Government College, Ogoja', state: 'Cross River' },
    { name: 'Federal Science and Technical College, Calabar', state: 'Cross River' },
    { name: 'Government Secondary School, Calabar', state: 'Cross River' },
    { name: 'Hope Waddell Training Institution, Calabar', state: 'Cross River' },
    { name: 'St. Patrick\'s Secondary School, Calabar', state: 'Cross River' },
    { name: 'Mary Slessor Secondary School, Calabar', state: 'Cross River' },
    { name: 'Regina Pacis Secondary School, Calabar', state: 'Cross River' },
    { name: 'Army Children Secondary School, Calabar', state: 'Cross River' },
    { name: 'Nigerian Navy Secondary School, Calabar', state: 'Cross River' },
    { name: 'Day Spring Secondary School, Calabar', state: 'Cross River' },
    { name: 'Nigerian Tulip International College, Calabar', state: 'Cross River' },

    // ================ DELTA ================
    { name: 'Federal Government College, Warri', state: 'Delta' },
    { name: 'Federal Government College, Agbor', state: 'Delta' },
    { name: 'Federal Science and Technical College, Asaba', state: 'Delta' },
    { name: 'Government College, Ughelli', state: 'Delta' },
    { name: 'St. Patrick\'s College, Asaba', state: 'Delta' },
    { name: 'St. George\'s Grammar School, Warri', state: 'Delta' },
    { name: 'Ighomena Secondary School, Agbor', state: 'Delta' },
    { name: 'West End Secondary School, Asaba', state: 'Delta' },
    { name: 'Urhobo College, Effurun', state: 'Delta' },
    { name: 'Nigerian Tulip International College, Warri', state: 'Delta' },
    { name: 'Grandville Secondary School, Agbor', state: 'Delta' },
    { name: 'Hebron Academy, Ekpan', state: 'Delta' },
    { name: 'BESWA International School, Ughelli', state: 'Delta' },

    // ================ EBONYI ================
    { name: 'Federal Government College, Abakaliki', state: 'Ebonyi' },
    { name: 'Federal Science and Technical College, Abakaliki', state: 'Ebonyi' },
    { name: 'Government Secondary School, Abakaliki', state: 'Ebonyi' },
    { name: 'Holy Child Secondary School, Abakaliki', state: 'Ebonyi' },
    { name: 'St. Joseph\'s Secondary School, Abakaliki', state: 'Ebonyi' },
    { name: 'Ishi High School, Ebonyi', state: 'Ebonyi' },
    { name: 'Government Technical College, Abakaliki', state: 'Ebonyi' },
    { name: 'Prescott International School, Abakaliki', state: 'Ebonyi' },
    { name: 'Marvellous City Academy, Abakaliki', state: 'Ebonyi' },
    { name: 'Nigerian Tulip International College, Abakaliki', state: 'Ebonyi' },

    // ================ EDO ================
    { name: 'Federal Government College, Benin', state: 'Edo' },
    { name: 'Federal Government Girls College, Benin', state: 'Edo' },
    { name: 'Federal Science and Technical College, Benin', state: 'Edo' },
    { name: 'Western Boys High School, Benin City', state: 'Edo' },
    { name: 'Edo College, Benin City', state: 'Edo' },
    { name: 'Immaculate Conception College, Benin City', state: 'Edo' },
    { name: 'Government Secondary School, Benin City', state: 'Edo' },
    { name: 'St. Maria Goretti Girls Secondary School, Benin City', state: 'Edo' },
    { name: 'Army Day Secondary School, Benin City', state: 'Edo' },
    { name: 'Igbinedion Education Centre, Benin City', state: 'Edo' },
    { name: 'Word of Faith International School, Benin City', state: 'Edo' },
    { name: 'Starry Light International School, Benin City', state: 'Edo' },
    { name: 'Nigerian Tulip International College, Benin', state: 'Edo' },

    // ================ EKITI ================
    { name: 'Federal Government College, Oye-Ekiti', state: 'Ekiti' },
    { name: 'Federal Government College, Ijero-Ekiti', state: 'Ekiti' },
    { name: 'Federal Science and Technical College, Ikole-Ekiti', state: 'Ekiti' },
    { name: 'Government College, Ikere-Ekiti', state: 'Ekiti' },
    { name: 'Christ\'s School, Ado-Ekiti', state: 'Ekiti' },
    { name: 'St. Louis Secondary School, Ado-Ekiti', state: 'Ekiti' },
    { name: 'Baptist High School, Ado-Ekiti', state: 'Ekiti' },
    { name: 'St. Michael\'s Secondary School, Ado-Ekiti', state: 'Ekiti' },
    { name: 'Annunciation School, Ido-Ekiti', state: 'Ekiti' },
    { name: 'Vale College, Ado-Ekiti', state: 'Ekiti' },
    { name: 'Bishy International School, Ado-Ekiti', state: 'Ekiti' },
    { name: 'Revelation Academy, Ado-Ekiti', state: 'Ekiti' },

    // ================ ENUGU ================
    { name: 'Federal Government College, Enugu', state: 'Enugu' },
    { name: 'Federal Government Girls College, Lejja', state: 'Enugu' },
    { name: 'Federal Science and Technical College, Enugu', state: 'Enugu' },
    { name: 'Queen\'s School, Enugu', state: 'Enugu' },
    { name: 'College of the Immaculate Conception, Enugu', state: 'Enugu' },
    { name: 'Holy Rosary College, Enugu', state: 'Enugu' },
    { name: 'St. Patrick\'s Secondary School, Enugu', state: 'Enugu' },
    { name: 'Government Secondary School, Udi', state: 'Enugu' },
    { name: 'University of Nigeria Secondary School, Nsukka', state: 'Enugu' },
    { name: 'Marist Comprehensive College, Nsukka', state: 'Enugu' },
    { name: 'St. Theresa\'s College, Nsukka', state: 'Enugu' },
    { name: 'Nigerian Tulip International College, Enugu', state: 'Enugu' },
    { name: 'Claret Academy, Enugu', state: 'Enugu' },

    // ================ FCT (ABUJA) ================
    { name: 'Federal Government College, Bwari', state: 'FCT (Abuja)' },
    { name: 'Federal Government College, Apo', state: 'FCT (Abuja)' },
    { name: 'Federal Science and Technical College, Garki', state: 'FCT (Abuja)' },
    { name: 'Government Secondary School, Garki', state: 'FCT (Abuja)' },
    { name: 'Government Secondary School, Wuse', state: 'FCT (Abuja)' },
    { name: 'Government Secondary School, Kubwa', state: 'FCT (Abuja)' },
    { name: 'Government Secondary School, Kwali', state: 'FCT (Abuja)' },
    { name: 'Loyola Jesuit College, Abuja', state: 'FCT (Abuja)' },
    { name: 'Nigerian Tulip International College, Abuja', state: 'FCT (Abuja)' },
    { name: 'British International School, Abuja', state: 'FCT (Abuja)' },
    { name: 'American International School, Abuja', state: 'FCT (Abuja)' },
    { name: 'Whitesands School, Abuja', state: 'FCT (Abuja)' },
    { name: 'Lifeforte International School, Abuja', state: 'FCT (Abuja)' },
    { name: 'Lead British International School, Abuja', state: 'FCT (Abuja)' },
    { name: 'Durham International School, Abuja', state: 'FCT (Abuja)' },

    // ================ GOMBE ================
    { name: 'Federal Government College, Gombe', state: 'Gombe' },
    { name: 'Federal Government College, Kumo', state: 'Gombe' },
    { name: 'Federal Science and Technical College, Gombe', state: 'Gombe' },
    { name: 'Government Secondary School, Gombe', state: 'Gombe' },
    { name: 'Government Girls Secondary School, Gombe', state: 'Gombe' },
    { name: 'Command Secondary School, Gombe', state: 'Gombe' },
    { name: 'Nigerian Tulip International College, Gombe', state: 'Gombe' },
    { name: 'Burndeavours International Academy, Gombe', state: 'Gombe' },
    { name: 'Standard International School, Gombe', state: 'Gombe' },
    { name: 'Special Science Secondary School, Kumo', state: 'Gombe' },

    // ================ IMO ================
    { name: 'Federal Government College, Owerri', state: 'Imo' },
    { name: 'Federal Government College, Okigwe', state: 'Imo' },
    { name: 'Federal Science and Technical College, Owerri', state: 'Imo' },
    { name: 'Government Secondary School, Owerri', state: 'Imo' },
    { name: 'Emmanuel College, Owerri', state: 'Imo' },
    { name: 'Holy Ghost College, Owerri', state: 'Imo' },
    { name: 'Girls Secondary School, Umuguma', state: 'Imo' },
    { name: 'St. Patrick\'s College, Owerri', state: 'Imo' },
    { name: 'Nigerian Navy Secondary School, Owerri', state: 'Imo' },
    { name: 'Nigerian Tulip International College, Owerri', state: 'Imo' },
    { name: 'Ideal International School, Owerri', state: 'Imo' },
    { name: 'Dombo International School, Owerri', state: 'Imo' },
    { name: 'Dove International School, Owerri', state: 'Imo' },

    // ================ JIGAWA ================
    { name: 'Federal Government College, Dutse', state: 'Jigawa' },
    { name: 'Federal Government College, Hadejia', state: 'Jigawa' },
    { name: 'Federal Science and Technical College, Dutse', state: 'Jigawa' },
    { name: 'Government Secondary School, Dutse', state: 'Jigawa' },
    { name: 'Government Science and Technical College, Dutse', state: 'Jigawa' },
    { name: 'Government Girls Secondary School, Dutse', state: 'Jigawa' },
    { name: 'Government Secondary School, Gumel', state: 'Jigawa' },
    { name: 'Al-Bayan International School, Dutse', state: 'Jigawa' },
    { name: 'Khadija International School, Majia', state: 'Jigawa' },
    { name: 'Nigerian Tulip International College, Dutse', state: 'Jigawa' },

    // ================ KADUNA ================
    { name: 'Federal Government College, Kaduna', state: 'Kaduna' },
    { name: 'Federal Government Girls College, Kaduna', state: 'Kaduna' },
    { name: 'Federal Science and Technical College, Kaduna', state: 'Kaduna' },
    { name: 'Barewa College, Zaria', state: 'Kaduna' },
    { name: 'Queen Elizabeth School, Kaduna', state: 'Kaduna' },
    { name: 'Government Secondary School, Kaduna', state: 'Kaduna' },
    { name: 'Government College, Kaduna', state: 'Kaduna' },
    { name: 'St. Joseph\'s Secondary School, Zaria', state: 'Kaduna' },
    { name: 'Command Day Secondary School, Kaduna', state: 'Kaduna' },
    { name: 'Nigerian Tulip International College, Kaduna', state: 'Kaduna' },
    { name: 'British International School, Kaduna', state: 'Kaduna' },
    { name: 'Essence International School, Kaduna', state: 'Kaduna' },
    { name: 'The Ambassador School, Kaduna', state: 'Kaduna' },

    // ================ KANO ================
    { name: 'Federal Government College, Kano', state: 'Kano' },
    { name: 'Federal Government Girls College, Kano', state: 'Kano' },
    { name: 'Federal Science and Technical College, Kano', state: 'Kano' },
    { name: 'Government Secondary School, Kano', state: 'Kano' },
    { name: 'Government College, Kano', state: 'Kano' },
    { name: 'Rumfa College, Kano', state: 'Kano' },
    { name: 'Girls Secondary School, Kano', state: 'Kano' },
    { name: 'Science and Technical College, Kano', state: 'Kano' },
    { name: 'Nigerian Tulip International College, Kano', state: 'Kano' },
    { name: 'Al-Mumtaz International School, Kano', state: 'Kano' },
    { name: 'Islamabad International School, Kano', state: 'Kano' },
    { name: 'AMA International Academy, Kano', state: 'Kano' },
    { name: 'Capital City International School, Kano', state: 'Kano' },

    // ================ KATSINA ================
    { name: 'Federal Government College, Katsina', state: 'Katsina' },
    { name: 'Federal Government College, Daura', state: 'Katsina' },
    { name: 'Federal Science and Technical College, Katsina', state: 'Katsina' },
    { name: 'Government Secondary School, Katsina', state: 'Katsina' },
    { name: 'Government College, Katsina', state: 'Katsina' },
    { name: 'Katsina Science School, Katsina', state: 'Katsina' },
    { name: 'Government Girls Secondary School, Katsina', state: 'Katsina' },
    { name: 'Nigerian Tulip International College, Katsina', state: 'Katsina' },
    { name: 'Al-Qalam International School, Katsina', state: 'Katsina' },
    { name: 'Khalid Academy, Katsina', state: 'Katsina' },

    // ================ KEBBI ================
    { name: 'Federal Government College, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Federal Government College, Yauri', state: 'Kebbi' },
    { name: 'Federal Science and Technical College, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Government Secondary School, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Government College, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Government Girls Secondary School, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Nigerian Tulip International College, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Al-Bayan International School, Birnin Kebbi', state: 'Kebbi' },
    { name: 'Kebbi State Science Academy, Zuru', state: 'Kebbi' },

    // ================ KOGI ================
    { name: 'Federal Government College, Okene', state: 'Kogi' },
    { name: 'Federal Government College, Kabba', state: 'Kogi' },
    { name: 'Federal Science and Technical College, Lokoja', state: 'Kogi' },
    { name: 'Government Secondary School, Lokoja', state: 'Kogi' },
    { name: 'Government College, Kabba', state: 'Kogi' },
    { name: 'Government Girls Secondary School, Okene', state: 'Kogi' },
    { name: 'St. Augustine\'s College, Kabba', state: 'Kogi' },
    { name: 'St. Peter\'s College, Idah', state: 'Kogi' },
    { name: 'Nigerian Tulip International College, Lokoja', state: 'Kogi' },
    { name: 'Salem International School, Lokoja', state: 'Kogi' },
    { name: 'Excel Academy, Lokoja', state: 'Kogi' },
    { name: 'Mount Merci International School, Lokoja', state: 'Kogi' },

    // ================ KWARA ================
    { name: 'Federal Government College, Ilorin', state: 'Kwara' },
    { name: 'Federal Government College, Jebba', state: 'Kwara' },
    { name: 'Federal Science and Technical College, Ilorin', state: 'Kwara' },
    { name: 'Government High School, Ilorin', state: 'Kwara' },
    { name: 'Government Secondary School, Ilorin', state: 'Kwara' },
    { name: 'Queen Elizabeth School, Ilorin', state: 'Kwara' },
    { name: 'St. Anthony\'s Secondary School, Ilorin', state: 'Kwara' },
    { name: 'Offa Grammar School, Offa', state: 'Kwara' },
    { name: 'Nigerian Tulip International College, Ilorin', state: 'Kwara' },
    { name: 'Havard Wilson International School, Ilorin', state: 'Kwara' },
    { name: 'Word of Faith International School, Ilorin', state: 'Kwara' },
    { name: 'Landmark College, Ilorin', state: 'Kwara' },
    { name: 'Baptist High School, Ilorin', state: 'Kwara' },

    // ================ LAGOS ================
    { name: 'King\'s College, Lagos', state: 'Lagos' },
    { name: 'Queen\'s College, Lagos', state: 'Lagos' },
    { name: 'Federal Government College, Ijanikin', state: 'Lagos' },
    { name: 'Federal Science and Technical College, Lagos', state: 'Lagos' },
    { name: 'Baptist Academy, Lagos', state: 'Lagos' },
    { name: 'St. Gregory\'s College, Lagos', state: 'Lagos' },
    { name: 'CMS Grammar School, Lagos', state: 'Lagos' },
    { name: 'Igbobi College, Lagos', state: 'Lagos' },
    { name: 'Methodist Boys High School, Lagos', state: 'Lagos' },
    { name: 'Eko Boys High School, Lagos', state: 'Lagos' },
    { name: 'St. Finbarr\'s College, Akoka', state: 'Lagos' },
    { name: 'Our Lady of Apostles Secondary School, Ikeja', state: 'Lagos' },
    { name: 'Holy Child College, Lagos', state: 'Lagos' },
    { name: 'St. Leo\'s Catholic School, Lagos', state: 'Lagos' },
    { name: 'British International School, Lekki', state: 'Lagos' },
    { name: 'American International School, Lagos', state: 'Lagos' },
    { name: 'Grange School, Lagos', state: 'Lagos' },
    { name: 'Greensprings School, Lagos', state: 'Lagos' },
    { name: 'Atlantic Hall, Epe', state: 'Lagos' },
    { name: 'Lagos Preparatory School, Lagos', state: 'Lagos' },
    { name: 'Nigerian Tulip International College, Lagos', state: 'Lagos' },
    { name: 'Rainbow College, Lagos', state: 'Lagos' },
    { name: 'Southfield School, Lagos', state: 'Lagos' },
    { name: 'Dowen College, Lagos', state: 'Lagos' },
    { name: 'Chrisland College, Lagos', state: 'Lagos' },
    { name: 'Whitestone School, Lagos', state: 'Lagos' },

    // ================ NASARAWA ================
    { name: 'Federal Government College, Keffi', state: 'Nasarawa' },
    { name: 'Federal Government College, Lafia', state: 'Nasarawa' },
    { name: 'Federal Science and Technical College, Keffi', state: 'Nasarawa' },
    { name: 'Government Secondary School, Keffi', state: 'Nasarawa' },
    { name: 'Government Secondary School, Lafia', state: 'Nasarawa' },
    { name: 'Government Girls Secondary School, Akwanga', state: 'Nasarawa' },
    { name: 'Science Secondary School, Mararaba', state: 'Nasarawa' },
    { name: 'Bingham Academy, Keffi', state: 'Nasarawa' },
    { name: 'Nigerian Tulip International College, Keffi', state: 'Nasarawa' },
    { name: 'Excel Academy, Lafia', state: 'Nasarawa' },
    { name: 'Goodnews International School, Karu', state: 'Nasarawa' },

    // ================ NIGER ================
    { name: 'Federal Government College, Bida', state: 'Niger' },
    { name: 'Federal Government College, Minna', state: 'Niger' },
    { name: 'Federal Government Academy, Suleja', state: 'Niger' },
    { name: 'Federal Science and Technical College, Minna', state: 'Niger' },
    { name: 'Government Secondary School, Minna', state: 'Niger' },
    { name: 'Government College, Minna', state: 'Niger' },
    { name: 'Government Girls Secondary School, Minna', state: 'Niger' },
    { name: 'Zuma Memorial Secondary School, Suleja', state: 'Niger' },
    { name: 'Nigerian Tulip International College, Minna', state: 'Niger' },
    { name: 'Royal Children Academy, Minna', state: 'Niger' },
    { name: 'Olive Shuttle International School, Bida', state: 'Niger' },
    { name: 'City Academy, Minna', state: 'Niger' },

    // ================ OGUN ================
    { name: 'Federal Government College, Odogbolu', state: 'Ogun' },
    { name: 'Federal Government College, Sagamu', state: 'Ogun' },
    { name: 'Federal Science and Technical College, Ijebu-Ode', state: 'Ogun' },
    { name: 'Baptist Boys High School, Abeokuta', state: 'Ogun' },
    { name: 'Abeokuta Grammar School, Abeokuta', state: 'Ogun' },
    { name: 'Ijebu-Ode Grammar School, Ijebu-Ode', state: 'Ogun' },
    { name: 'Remo Secondary School, Sagamu', state: 'Ogun' },
    { name: 'Anglican Girls Grammar School, Abeokuta', state: 'Ogun' },
    { name: 'St. Peter\'s College, Abeokuta', state: 'Ogun' },
    { name: 'Our Lady of Apostles Secondary School, Ijebu-Ode', state: 'Ogun' },
    { name: 'Bells Comprehensive School, Ota', state: 'Ogun' },
    { name: 'Covenant University Secondary School, Ota', state: 'Ogun' },
    { name: 'Nigerian Tulip International College, Abeokuta', state: 'Ogun' },
    { name: 'Babcock International School, Ilisan', state: 'Ogun' },
    { name: 'Chrisland School, Ota', state: 'Ogun' },

    // ================ ONDO ================
    { name: 'Federal Government College, Akure', state: 'Ondo' },
    { name: 'Federal Government College, Ikare', state: 'Ondo' },
    { name: 'Federal Science and Technical College, Akure', state: 'Ondo' },
    { name: 'Government Secondary School, Akure', state: 'Ondo' },
    { name: 'Oyemekun Grammar School, Akure', state: 'Ondo' },
    { name: 'St. Thomas Aquinas College, Akure', state: 'Ondo' },
    { name: 'St. Joseph\'s College, Ondo', state: 'Ondo' },
    { name: 'Imade College, Owo', state: 'Ondo' },
    { name: 'Aquinas College, Akure', state: 'Ondo' },
    { name: 'Elizade International School, Ilara-Mokin', state: 'Ondo' },
    { name: 'Nigerian Tulip International College, Akure', state: 'Ondo' },
    { name: 'Achievers International School, Owo', state: 'Ondo' },

    // ================ OSUN ================
    { name: 'Federal Government College, Osogbo', state: 'Osun' },
    { name: 'Federal Government College, Ilesa', state: 'Osun' },
    { name: 'Federal Science and Technical College, Iwo', state: 'Osun' },
    { name: 'Government High School, Osogbo', state: 'Osun' },
    { name: 'Ilesa Grammar School, Ilesa', state: 'Osun' },
    { name: 'Ataoja High School, Osogbo', state: 'Osun' },
    { name: 'Ife Grammar School, Ile-Ife', state: 'Osun' },
    { name: 'St. Charles College, Osogbo', state: 'Osun' },
    { name: 'St. Lawrence College, Ile-Ife', state: 'Osun' },
    { name: 'Osogbo Grammar School, Osogbo', state: 'Osun' },
    { name: 'Nigerian Tulip International College, Osogbo', state: 'Osun' },
    { name: 'Redeemer\'s International School, Ede', state: 'Osun' },
    { name: 'Fountain International School, Osogbo', state: 'Osun' },

    // ================ OYO ================
    { name: 'Federal Government College, Ibadan', state: 'Oyo' },
    { name: 'Federal Government College, Oyo', state: 'Oyo' },
    { name: 'Federal Science and Technical College, Ibadan', state: 'Oyo' },
    { name: 'Ibadan Grammar School, Ibadan', state: 'Oyo' },
    { name: 'Government College, Ibadan', state: 'Oyo' },
    { name: 'St. Anne\'s School, Ibadan', state: 'Oyo' },
    { name: 'Wesley College, Ibadan', state: 'Oyo' },
    { name: 'Queen\'s School, Ibadan', state: 'Oyo' },
    { name: 'Ogbomoso Grammar School, Ogbomoso', state: 'Oyo' },
    { name: 'Olivet Heights, Oyo', state: 'Oyo' },
    { name: 'International School, Ibadan', state: 'Oyo' },
    { name: 'Nigerian Tulip International College, Ibadan', state: 'Oyo' },
    { name: 'Lead City International School, Ibadan', state: 'Oyo' },
    { name: 'Divine Wisdom Academy, Ibadan', state: 'Oyo' },
    { name: 'British International School, Ibadan', state: 'Oyo' },

    // ================ PLATEAU ================
    { name: 'Federal Government College, Jos', state: 'Plateau' },
    { name: 'Federal Government Girls College, Jos', state: 'Plateau' },
    { name: 'Federal Science and Technical College, Jos', state: 'Plateau' },
    { name: 'Government Secondary School, Jos', state: 'Plateau' },
    { name: 'Government Secondary School, Pankshin', state: 'Plateau' },
    { name: 'St. John\'s College, Jos', state: 'Plateau' },
    { name: 'St. Louis College, Shendam', state: 'Plateau' },
    { name: 'Mount Saint Gabriel\'s Secondary School, Jos', state: 'Plateau' },
    { name: 'Nigerian Tulip International College, Jos', state: 'Plateau' },
    { name: 'British International School, Jos', state: 'Plateau' },
    { name: 'NECO Science School, Jos', state: 'Plateau' },
    { name: 'Miracle International School, Jos', state: 'Plateau' },

    // ================ RIVERS ================
    { name: 'Federal Government College, Port Harcourt', state: 'Rivers' },
    { name: 'Federal Government Girls College, Port Harcourt', state: 'Rivers' },
    { name: 'Federal Science and Technical College, Port Harcourt', state: 'Rivers' },
    { name: 'Government Secondary School, Port Harcourt', state: 'Rivers' },
    { name: 'Government Comprehensive Secondary School, Port Harcourt', state: 'Rivers' },
    { name: 'Stella Maris College, Port Harcourt', state: 'Rivers' },
    { name: 'Holy Rosary College, Port Harcourt', state: 'Rivers' },
    { name: 'St. Mary\'s School, Port Harcourt', state: 'Rivers' },
    { name: 'Archdeacon Crowther Memorial Girls School, Port Harcourt', state: 'Rivers' },
    { name: 'Nigerian Tulip International College, Port Harcourt', state: 'Rivers' },
    { name: 'British International School, Port Harcourt', state: 'Rivers' },
    { name: 'Bloombreed College, Port Harcourt', state: 'Rivers' },
    { name: 'Jephthah Comprehensive College, Port Harcourt', state: 'Rivers' },
    { name: 'Bethel International School, Port Harcourt', state: 'Rivers' },

    // ================ SOKOTO ================
    { name: 'Federal Government College, Sokoto', state: 'Sokoto' },
    { name: 'Federal Government Girls College, Sokoto', state: 'Sokoto' },
    { name: 'Federal Science and Technical College, Sokoto', state: 'Sokoto' },
    { name: 'Government Secondary School, Sokoto', state: 'Sokoto' },
    { name: 'Government College, Sokoto', state: 'Sokoto' },
    { name: 'Nagarta College, Sokoto', state: 'Sokoto' },
    { name: 'Government Girls Secondary School, Sokoto', state: 'Sokoto' },
    { name: 'Nigerian Tulip International College, Sokoto', state: 'Sokoto' },
    { name: 'Al-Nur International School, Sokoto', state: 'Sokoto' },
    { name: 'Sultan Bello Science and Technical College, Sokoto', state: 'Sokoto' },

    // ================ TARABA ================
    { name: 'Federal Government College, Jalingo', state: 'Taraba' },
    { name: 'Federal Government College, Wukari', state: 'Taraba' },
    { name: 'Federal Science and Technical College, Jalingo', state: 'Taraba' },
    { name: 'Government Secondary School, Jalingo', state: 'Taraba' },
    { name: 'Government Girls Secondary School, Jalingo', state: 'Taraba' },
    { name: 'Government Secondary School, Wukari', state: 'Taraba' },
    { name: 'Nigerian Army Secondary School, Jalingo', state: 'Taraba' },
    { name: 'Nigerian Tulip International College, Jalingo', state: 'Taraba' },
    { name: 'Royal Academy, Jalingo', state: 'Taraba' },
    { name: 'Destiny International School, Jalingo', state: 'Taraba' },

    // ================ YOBE ================
    { name: 'Federal Government College, Damaturu', state: 'Yobe' },
    { name: 'Federal Government College, Potiskum', state: 'Yobe' },
    { name: 'Federal Science and Technical College, Damaturu', state: 'Yobe' },
    { name: 'Government Secondary School, Damaturu', state: 'Yobe' },
    { name: 'Government Science and Technical College, Potiskum', state: 'Yobe' },
    { name: 'Government Girls Secondary School, Damaturu', state: 'Yobe' },
    { name: 'Government Secondary School, Gashua', state: 'Yobe' },
    { name: 'Nigerian Tulip International College, Damaturu', state: 'Yobe' },
    { name: 'Al-Ansar International School, Damaturu', state: 'Yobe' },
    { name: 'Mairi International School, Damaturu', state: 'Yobe' },

    // ================ ZAMFARA ================
    { name: 'Federal Government College, Gusau', state: 'Zamfara' },
    { name: 'Federal Science and Technical College, Gusau', state: 'Zamfara' },
    { name: 'Government Secondary School, Gusau', state: 'Zamfara' },
    { name: 'Government Girls Secondary School, Gusau', state: 'Zamfara' },
    { name: 'Government Technical College, Gusau', state: 'Zamfara' },
    { name: 'Government Secondary School, Kaura Namoda', state: 'Zamfara' },
    { name: 'Nigerian Tulip International College, Gusau', state: 'Zamfara' },
    { name: 'Al-Mannan International School, Gusau', state: 'Zamfara' },
    { name: 'Huda International School, Gusau', state: 'Zamfara' },
    { name: 'Government Day Secondary School, Talata Mafara', state: 'Zamfara' },
  ],

  // ==========================================================================
  // OTHER AFRICAN COUNTRIES
  // ==========================================================================

  'Kenya': [
    { name: 'Alliance High School, Kikuyu', state: 'Kiambu, Kenya' },
    { name: 'St. George\'s College, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'St. Mary\'s School, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'International School of Kenya, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'Mpesa Foundation Academy, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'Hillcrest International School, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'Strathmore School, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'The Kenya High School, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'Loreto Convent Msongari, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'Mangu High School, Thika', state: 'Kiambu, Kenya' },
    { name: 'Lenana School, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'St. Mary\'s School, Yala', state: 'Siaya, Kenya' },
    { name: 'Aga Khan Academy, Mombasa', state: 'Mombasa, Kenya' },
    { name: 'Brookhouse International School, Nairobi', state: 'Nairobi, Kenya' },
    { name: 'Braeburn School, Nairobi', state: 'Nairobi, Kenya' },
  ],

  'Ghana': [
    { name: 'Achimota School, Accra', state: 'Greater Accra, Ghana' },
    { name: 'Ghana National College, Cape Coast', state: 'Central, Ghana' },
    { name: 'St. Augustine\'s College, Cape Coast', state: 'Central, Ghana' },
    { name: 'Wesley Girls High School, Cape Coast', state: 'Central, Ghana' },
    { name: 'Prempeh College, Kumasi', state: 'Ashanti, Ghana' },
    { name: 'Mfantsipim School, Cape Coast', state: 'Central, Ghana' },
    { name: 'Holy Child School, Cape Coast', state: 'Central, Ghana' },
    { name: 'St. Louis Senior High School, Kumasi', state: 'Ashanti, Ghana' },
    { name: 'Opoku Ware School, Kumasi', state: 'Ashanti, Ghana' },
    { name: 'SOS Hermann Gmeiner International College, Tema', state: 'Greater Accra, Ghana' },
    { name: 'Lincoln Community School, Accra', state: 'Greater Accra, Ghana' },
    { name: 'Ghana International School, Accra', state: 'Greater Accra, Ghana' },
    { name: 'Bishop Herman College, Kpando', state: 'Volta, Ghana' },
    { name: 'St. Peter\'s Boys School, Nkwatia', state: 'Eastern, Ghana' },
    { name: 'Accra Academy, Accra', state: 'Greater Accra, Ghana' },
  ],

  'South Africa': [
    { name: 'St. John\'s College, Johannesburg', state: 'Gauteng, South Africa' },
    { name: 'Bishops Diocesan College, Cape Town', state: 'Western Cape, South Africa' },
    { name: 'St. Joseph\'s College, Cape Town', state: 'Western Cape, South Africa' },
    { name: 'King Edward VII School, Johannesburg', state: 'Gauteng, South Africa' },
    { name: 'Wynberg Boys High School, Cape Town', state: 'Western Cape, South Africa' },
    { name: 'Pretoria Boys High School, Pretoria', state: 'Gauteng, South Africa' },
    { name: 'The Diocesan School for Girls, Grahamstown', state: 'Eastern Cape, South Africa' },
    { name: 'Hilton College, Hilton', state: 'KwaZulu-Natal, South Africa' },
    { name: 'Michaelhouse, Balgowan', state: 'KwaZulu-Natal, South Africa' },
    { name: 'Roedean School, Johannesburg', state: 'Gauteng, South Africa' },
    { name: 'St. Andrew\'s College, Grahamstown', state: 'Eastern Cape, South Africa' },
    { name: 'South African College Schools, Cape Town', state: 'Western Cape, South Africa' },
    { name: 'American International School of Johannesburg', state: 'Gauteng, South Africa' },
    { name: 'Crawford College, Johannesburg', state: 'Gauteng, South Africa' },
    { name: 'Sacred Heart College, Johannesburg', state: 'Gauteng, South Africa' },
  ],

  'Uganda': [
    { name: 'St. Charles Lwanga, Kampala', state: 'Central, Uganda' },
    { name: 'King\'s College Budo, Kampala', state: 'Central, Uganda' },
    { name: 'Gayaza High School, Gayaza', state: 'Central, Uganda' },
    { name: 'Namilyango College, Namilyango', state: 'Central, Uganda' },
    { name: 'St. Mary\'s College Kisubi, Kisubi', state: 'Central, Uganda' },
    { name: 'Trinity College Nabbingo, Nabbingo', state: 'Central, Uganda' },
    { name: 'Mount St. Mary\'s College Namagunga, Namagunga', state: 'Central, Uganda' },
    { name: 'International School of Uganda, Kampala', state: 'Central, Uganda' },
    { name: 'Aga Khan High School, Kampala', state: 'Central, Uganda' },
    { name: 'Kololo High School, Kampala', state: 'Central, Uganda' },
    { name: 'St. Joseph\'s College, Layibi', state: 'Northern, Uganda' },
    { name: 'Kibuli Secondary School, Kampala', state: 'Central, Uganda' },
    { name: 'Busoga College Mwiri, Jinja', state: 'Eastern, Uganda' },
  ],

  'Ethiopia': [
    { name: 'SOS Hermann Gmeiner School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'Sandford International School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'International Community School of Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'St. Joseph\'s School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'Lideta Catholic Cathedral School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'Bole International School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'Catholic Cathedral School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
    { name: 'British International School, Addis Ababa', state: 'Addis Ababa, Ethiopia' },
  ],

  "C\u00f4te d'Ivoire": [
    { name: 'Lyc\u00e9e Sainte Famille, Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'Lyc\u00e9e Classique d\'Abidjan, Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'Lyc\u00e9e Blaise Pascal, Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'International Community School of Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'Ecole Notre Dame des Ap\u00f4tres, Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'Les Collines de l\'Espace, Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'Lyc\u00e9e Fran\u00e7ais d\'Abidjan, Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
    { name: 'American International School of Abidjan', state: 'Abidjan, C\u00f4te d\'Ivoire' },
  ],

  'Tanzania': [
    { name: 'St. Francis College, Pugu', state: 'Dar es Salaam, Tanzania' },
    { name: 'International School of Tanganyika, Dar es Salaam', state: 'Dar es Salaam, Tanzania' },
    { name: 'Kibasila Secondary School, Dar es Salaam', state: 'Dar es Salaam, Tanzania' },
    { name: 'St. Joseph\'s Secondary School, Dar es Salaam', state: 'Dar es Salaam, Tanzania' },
    { name: 'Feza International School, Dar es Salaam', state: 'Dar es Salaam, Tanzania' },
    { name: 'Aga Khan Mzizima Secondary School, Dar es Salaam', state: 'Dar es Salaam, Tanzania' },
    { name: 'Arusha Secondary School, Arusha', state: 'Arusha, Tanzania' },
    { name: 'Kilimanjaro International School, Moshi', state: 'Kilimanjaro, Tanzania' },
    { name: 'Braeburn School, Arusha', state: 'Arusha, Tanzania' },
    { name: 'Loyola High School, Dar es Salaam', state: 'Dar es Salaam, Tanzania' },
  ],

  'Rwanda': [
    { name: 'Groupe Scolaire Officiel de Butare, Butare', state: 'Huye, Rwanda' },
    { name: 'Lyc\u00e9e de Kigali, Kigali', state: 'Kigali, Rwanda' },
    { name: 'Green Hills Academy, Kigali', state: 'Kigali, Rwanda' },
    { name: 'International School of Rwanda, Kigali', state: 'Kigali, Rwanda' },
    { name: 'St. Ignatius School, Kigali', state: 'Kigali, Rwanda' },
    { name: 'FAWE Girls School, Kigali', state: 'Kigali, Rwanda' },
    { name: 'Ecole Belge de Kigali, Kigali', state: 'Kigali, Rwanda' },
    { name: 'Gashora Girls Academy, Gashora', state: 'Eastern, Rwanda' },
  ],

  'Morocco': [
    { name: 'Lyc\u00e9e Lyautey, Casablanca', state: 'Casablanca, Morocco' },
    { name: 'Lyc\u00e9e Descartes, Rabat', state: 'Rabat, Morocco' },
    { name: 'Lyc\u00e9e Victor Hugo, Marrakech', state: 'Marrakech, Morocco' },
    { name: 'American School of Marrakesh', state: 'Marrakech, Morocco' },
    { name: 'Casablanca American School', state: 'Casablanca, Morocco' },
    { name: 'Rabat American School', state: 'Rabat, Morocco' },
    { name: 'George Washington Academy, Casablanca', state: 'Casablanca, Morocco' },
    { name: 'British Academy, Marrakech', state: 'Marrakech, Morocco' },
    { name: '\u00c9cole Active Bilingue, Casablanca', state: 'Casablanca, Morocco' },
    { name: 'Lyc\u00e9e Moulay Youssef, Rabat', state: 'Rabat, Morocco' },
  ],

  'Egypt': [
    { name: 'Cairo American College, Cairo', state: 'Cairo, Egypt' },
    { name: 'Cairo British School, Cairo', state: 'Cairo, Egypt' },
    { name: 'St. George\'s College, Cairo', state: 'Cairo, Egypt' },
    { name: 'Saint Mary\'s College, Cairo', state: 'Cairo, Egypt' },
    { name: 'El Alsson School, Cairo', state: 'Cairo, Egypt' },
    { name: 'New Cairo British International School', state: 'Cairo, Egypt' },
    { name: 'Schutz American School, Alexandria', state: 'Alexandria, Egypt' },
    { name: 'Victoria College, Alexandria', state: 'Alexandria, Egypt' },
    { name: 'Ramses College for Girls, Cairo', state: 'Cairo, Egypt' },
    { name: 'Malvern College Egypt, Cairo', state: 'Cairo, Egypt' },
    { name: 'The International School of Choueifat, Cairo', state: 'Cairo, Egypt' },
    { name: 'Al-Azhar Secondary School, Cairo', state: 'Cairo, Egypt' },
    { name: 'Modern Education School, Cairo', state: 'Cairo, Egypt' },
  ],

  'Algeria': [
    { name: 'Lyc\u00e9e International d\'Alger, Algiers', state: 'Algiers, Algeria' },
    { name: 'Lyc\u00e9e Descartes, Algiers', state: 'Algiers, Algeria' },
    { name: 'American International School of Algiers', state: 'Algiers, Algeria' },
    { name: 'British International School, Algiers', state: 'Algiers, Algeria' },
    { name: 'Lyc\u00e9e El Mokhtar, Algiers', state: 'Algiers, Algeria' },
    { name: 'Al Moudjahid Secondary School, Algiers', state: 'Algiers, Algeria' },
    { name: 'Ibn Rochd Secondary School, Algiers', state: 'Algiers, Algeria' },
  ],

  'Tunisia': [
    { name: 'Lyc\u00e9e Pierre Mend\u00e8s France, Tunis', state: 'Tunis, Tunisia' },
    { name: 'Lyc\u00e9e Gustave Flaubert, Tunis', state: 'Tunis, Tunisia' },
    { name: 'American Cooperative School of Tunis', state: 'Tunis, Tunisia' },
    { name: 'British School of Tunis', state: 'Tunis, Tunisia' },
    { name: 'Tunis International School', state: 'Tunis, Tunisia' },
    { name: 'Saint Joseph\'s School, Tunis', state: 'Tunis, Tunisia' },
    { name: 'Lyc\u00e9e Ariana, Ariana', state: 'Ariana, Tunisia' },
    { name: 'Sadiki College, Tunis', state: 'Tunis, Tunisia' },
  ],

  'Senegal': [
    { name: 'Lyc\u00e9e Jean Mermoz, Dakar', state: 'Dakar, Senegal' },
    { name: 'Lyc\u00e9e Fran\u00e7ais de Dakar', state: 'Dakar, Senegal' },
    { name: 'International School of Dakar', state: 'Dakar, Senegal' },
    { name: '\u00c9cole des Roches, Dakar', state: 'Dakar, Senegal' },
    { name: 'Lyc\u00e9e d\'Excellence Mariama Ba, Gor\u00e9e', state: 'Dakar, Senegal' },
    { name: 'West African College of the Atlantic, Dakar', state: 'Dakar, Senegal' },
    { name: 'Cours Sainte Marie de Hann, Dakar', state: 'Dakar, Senegal' },
    { name: 'Dakar Academy, Dakar', state: 'Dakar, Senegal' },
  ],

  'Cameroon': [
    { name: 'Lyc\u00e9e Classique d\'Ebolowa', state: 'South, Cameroon' },
    { name: 'Lyc\u00e9e G\u00e9n\u00e9ral Leclerc, Yaound\u00e9', state: 'Centre, Cameroon' },
    { name: 'Government Bilingual High School, Yaound\u00e9', state: 'Centre, Cameroon' },
    { name: 'American School of Yaound\u00e9', state: 'Centre, Cameroon' },
    { name: 'Rainbow International School, Douala', state: 'Littoral, Cameroon' },
    { name: 'St. Joseph\'s College Sasse, Buea', state: 'Southwest, Cameroon' },
    { name: 'Sacred Heart College, Bamenda', state: 'Northwest, Cameroon' },
    { name: 'Our Lady of Lourdes College, Molyko', state: 'Southwest, Cameroon' },
    { name: 'British School of Yaound\u00e9', state: 'Centre, Cameroon' },
  ],

  'Zambia': [
    { name: 'Munali Secondary School, Lusaka', state: 'Lusaka, Zambia' },
    { name: 'Kabulonga Secondary School, Lusaka', state: 'Lusaka, Zambia' },
    { name: 'St. Mary\'s Secondary School, Lusaka', state: 'Lusaka, Zambia' },
    { name: 'International School of Lusaka', state: 'Lusaka, Zambia' },
    { name: 'American International School of Lusaka', state: 'Lusaka, Zambia' },
    { name: 'Nkumbi International College, Lusaka', state: 'Lusaka, Zambia' },
    { name: 'David Kaunda Technical Secondary School, Lusaka', state: 'Lusaka, Zambia' },
    { name: 'Lusaka International Community School', state: 'Lusaka, Zambia' },
  ],

  'Zimbabwe': [
    { name: 'Prince Edward School, Harare', state: 'Harare, Zimbabwe' },
    { name: 'St. George\'s College, Harare', state: 'Harare, Zimbabwe' },
    { name: 'Arundel School, Harare', state: 'Harare, Zimbabwe' },
    { name: 'Ellis Robins School, Harare', state: 'Harare, Zimbabwe' },
    { name: 'St. John\'s College, Harare', state: 'Harare, Zimbabwe' },
    { name: 'Girls College, Harare', state: 'Harare, Zimbabwe' },
    { name: 'Churchill School, Harare', state: 'Harare, Zimbabwe' },
    { name: 'St. Mary\'s School, Harare', state: 'Harare, Zimbabwe' },
    { name: 'Falcon College, Esigodini', state: 'Matabeleland, Zimbabwe' },
    { name: 'Peterhouse Group, Marondera', state: 'Mashonaland East, Zimbabwe' },
  ],

  'Angola': [
    { name: 'Sagrada Esperan\u00e7a School, Luanda', state: 'Luanda, Angola' },
    { name: 'Col\u00e9gio Portugu\u00eas de Luanda', state: 'Luanda, Angola' },
    { name: 'Luanda International School', state: 'Luanda, Angola' },
    { name: 'British School of Luanda', state: 'Luanda, Angola' },
    { name: 'Col\u00e9gio S\u00e3o Francisco de Assis, Luanda', state: 'Luanda, Angola' },
  ],

  'Mozambique': [
    { name: 'Col\u00e9gio Franc\u00eas de Maputo', state: 'Maputo, Mozambique' },
    { name: 'American International School of Mozambique, Maputo', state: 'Maputo, Mozambique' },
    { name: 'British School of Maputo', state: 'Maputo, Mozambique' },
    { name: 'Col\u00e9gio Nossa Senhora de F\u00e1tima, Maputo', state: 'Maputo, Mozambique' },
    { name: 'Maputo International School', state: 'Maputo, Mozambique' },
  ],

  'Namibia': [
    { name: 'St. Paul\'s College, Windhoek', state: 'Khomas, Namibia' },
    { name: 'Windhoek International School', state: 'Khomas, Namibia' },
    { name: 'Windhoek High School', state: 'Khomas, Namibia' },
    { name: 'Concordia College, Windhoek', state: 'Khomas, Namibia' },
    { name: 'St. George\'s Diocesan School, Windhoek', state: 'Khomas, Namibia' },
  ],

  'Botswana': [
    { name: 'Maru a Pula School, Gaborone', state: 'South-East, Botswana' },
    { name: 'St. Joseph\'s College, Kgale', state: 'South-East, Botswana' },
    { name: 'Gaborone Secondary School', state: 'South-East, Botswana' },
    { name: 'Northside Secondary School, Gaborone', state: 'South-East, Botswana' },
    { name: 'Westwood International School, Gaborone', state: 'South-East, Botswana' },
  ],

  'Mauritius': [
    { name: 'Royal College of Curepipe', state: 'Plaines Wilhems, Mauritius' },
    { name: 'Le Bocage International School, Moka', state: 'Moka, Mauritius' },
    { name: 'St. Joseph\'s College, Curepipe', state: 'Plaines Wilhems, Mauritius' },
    { name: 'Queen Elizabeth College, Rose-Hill', state: 'Plaines Wilhems, Mauritius' },
    { name: 'Lycee La Bourdonnais, Curepipe', state: 'Plaines Wilhems, Mauritius' },
  ],

  'Sudan': [
    { name: 'Khartoum American School', state: 'Khartoum, Sudan' },
    { name: 'Khartoum International Community School', state: 'Khartoum, Sudan' },
    { name: 'Unity High School, Khartoum', state: 'Khartoum, Sudan' },
    { name: 'St. Joseph\'s School, Khartoum', state: 'Khartoum, Sudan' },
    { name: 'Comboni College, Khartoum', state: 'Khartoum, Sudan' },
  ],

  'South Sudan': [
    { name: 'Juba International School', state: 'Central Equatoria, South Sudan' },
    { name: 'Bright Star Secondary School, Juba', state: 'Central Equatoria, South Sudan' },
    { name: 'Rock International Academy, Juba', state: 'Central Equatoria, South Sudan' },
    { name: 'Juba College of Commerce Secondary School', state: 'Central Equatoria, South Sudan' },
  ],

  'Somalia': [
    { name: 'Mogadishu International School', state: 'Banaadir, Somalia' },
    { name: 'Al-Najah School, Mogadishu', state: 'Banaadir, Somalia' },
    { name: 'Jamaludin Secondary School, Mogadishu', state: 'Banaadir, Somalia' },
    { name: 'Sheikh Osman Secondary School, Mogadishu', state: 'Banaadir, Somalia' },
  ],

  'Libya': [
    { name: 'Tripoli International School', state: 'Tripoli, Libya' },
    { name: 'American School of Tripoli', state: 'Tripoli, Libya' },
    { name: 'British School of Tripoli', state: 'Tripoli, Libya' },
    { name: 'Lyc\u00e9e Fran\u00e7ais de Tripoli', state: 'Tripoli, Libya' },
    { name: 'Al-Hayat International School, Benghazi', state: 'Benghazi, Libya' },
  ],

  'Sierra Leone': [
    { name: 'St. Francis Secondary School, Freetown', state: 'Western Area, Sierra Leone' },
    { name: 'Bo School, Bo', state: 'Southern, Sierra Leone' },
    { name: 'Annie Walsh Memorial School, Freetown', state: 'Western Area, Sierra Leone' },
    { name: 'Prince of Wales School, Freetown', state: 'Western Area, Sierra Leone' },
    { name: 'St. Joseph\'s Secondary School, Freetown', state: 'Western Area, Sierra Leone' },
  ],

  'Liberia': [
    { name: 'Monrovia College', state: 'Montserrado, Liberia' },
    { name: 'American International School of Monrovia', state: 'Montserrado, Liberia' },
    { name: 'St. Patrick\'s High School, Monrovia', state: 'Montserrado, Liberia' },
    { name: 'Ricks Institute, Virginia', state: 'Montserrado, Liberia' },
    { name: 'Booker Washington Institute, Kakata', state: 'Margibi, Liberia' },
  ],

  'Guinea': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Albert Camus, Conakry', state: 'Conakry, Guinea' },
    { name: 'American International School of Conakry', state: 'Conakry, Guinea' },
    { name: 'Lyc\u00e9e 2 Octobre, Conakry', state: 'Conakry, Guinea' },
    { name: 'Sainte Marie de Conakry', state: 'Conakry, Guinea' },
  ],

  'Burkina Faso': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Saint-Exup\u00e9ry, Ouagadougou', state: 'Centre, Burkina Faso' },
    { name: 'International School of Ouagadougou', state: 'Centre, Burkina Faso' },
    { name: 'Lyc\u00e9e Philippe Zinda Kabor\u00e9, Ouagadougou', state: 'Centre, Burkina Faso' },
    { name: 'Lyc\u00e9e National, Bobo-Dioulasso', state: 'Hauts-Bassins, Burkina Faso' },
  ],

  'Mali': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Libert\u00e9, Bamako', state: 'Bamako, Mali' },
    { name: 'American International School of Bamako', state: 'Bamako, Mali' },
    { name: 'Lyc\u00e9e Public de Bamako', state: 'Bamako, Mali' },
    { name: 'Groupe Scolaire Les Angelots, Bamako', state: 'Bamako, Mali' },
    { name: 'Lyc\u00e9e Askia Mohamed, Bamako', state: 'Bamako, Mali' },
  ],

  'Niger': [
    { name: 'Lyc\u00e9e Fran\u00e7ais La Fontaine, Niamey', state: 'Niamey, Niger' },
    { name: 'American International School of Niamey', state: 'Niamey, Niger' },
    { name: 'Lyc\u00e9e National de Niamey', state: 'Niamey, Niger' },
    { name: 'Coll\u00e8ge Mariama, Niamey', state: 'Niamey, Niger' },
  ],

  'Chad': [
    { name: 'Lyc\u00e9e Fran\u00e7ais de N\u2019Djamena', state: 'N\'Djamena, Chad' },
    { name: 'American International School of N\'Djamena', state: 'N\'Djamena, Chad' },
    { name: 'Coll\u00e8ge Charles Lwanga, N\'Djamena', state: 'N\'Djamena, Chad' },
    { name: 'Lyc\u00e9e F\u00e9minin de N\'Djamena', state: 'N\'Djamena, Chad' },
  ],

  'Benin': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Jean Mermoz, Cotonou', state: 'Littoral, Benin' },
    { name: 'International School of Benin, Cotonou', state: 'Littoral, Benin' },
    { name: 'Coll\u00e8ge P\u00e8re Aupiais, Cotonou', state: 'Littoral, Benin' },
    { name: 'Lyc\u00e9e Toffa 1er, Porto-Novo', state: 'Ou\u00e9m\u00e9, Benin' },
    { name: 'Coll\u00e8ge Saint Michel, Cotonou', state: 'Littoral, Benin' },
  ],

  'Togo': [
    { name: 'Lyc\u00e9e Fran\u00e7ais de Lom\u00e9', state: 'Maritime, Togo' },
    { name: 'British School of Lom\u00e9', state: 'Maritime, Togo' },
    { name: 'Coll\u00e8ge Saint Joseph de Lom\u00e9', state: 'Maritime, Togo' },
    { name: 'Lyc\u00e9e de Tokoin, Lom\u00e9', state: 'Maritime, Togo' },
    { name: 'International School of Lom\u00e9', state: 'Maritime, Togo' },
  ],

  'Madagascar': [
    { name: 'Lyc\u00e9e Fran\u00e7ais d\'Antananarivo', state: 'Analamanga, Madagascar' },
    { name: 'American International School of Antananarivo', state: 'Analamanga, Madagascar' },
    { name: 'British School of Antananarivo', state: 'Analamanga, Madagascar' },
    { name: 'Coll\u00e8ge Saint-Michel, Antananarivo', state: 'Analamanga, Madagascar' },
    { name: 'Coll\u00e8ge Fran\u00e7ais Jules Verne, Antsirabe', state: 'Vakinankaratra, Madagascar' },
  ],

  'Congo DR': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Ren\u00e9 Descartes, Kinshasa', state: 'Kinshasa, DR Congo' },
    { name: 'American School of Kinshasa', state: 'Kinshasa, DR Congo' },
    { name: 'The International School of Kinshasa', state: 'Kinshasa, DR Congo' },
    { name: 'Coll\u00e8ge Boboto, Kinshasa', state: 'Kinshasa, DR Congo' },
    { name: 'Coll\u00e8ge Saint Joseph, Kinshasa', state: 'Kinshasa, DR Congo' },
    { name: 'Institut de la Gombe, Kinshasa', state: 'Kinshasa, DR Congo' },
    { name: 'Ecole Belge de Kinshasa', state: 'Kinshasa, DR Congo' },
  ],

  'Congo': [
    { name: 'Lyc\u00e9e Fran\u00e7ais de Brazzaville', state: 'Brazzaville, Congo' },
    { name: 'American International School of Brazzaville', state: 'Brazzaville, Congo' },
    { name: 'Coll\u00e8ge Chaminade, Brazzaville', state: 'Brazzaville, Congo' },
    { name: 'Lyc\u00e9e Savorgnan de Brazza, Brazzaville', state: 'Brazzaville, Congo' },
  ],

  'Gabon': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Blaise Pascal, Libreville', state: 'Estuaire, Gabon' },
    { name: 'American International School of Libreville', state: 'Estuaire, Gabon' },
    { name: 'Ruban Vert International School, Libreville', state: 'Estuaire, Gabon' },
    { name: 'Lyc\u00e9e National L\u00e9on Mba, Libreville', state: 'Estuaire, Gabon' },
  ],

  'Malawi': [
    { name: 'Kamuzu Academy, Kasungu', state: 'Central, Malawi' },
    { name: 'St. Andrew\'s International School, Blantyre', state: 'Southern, Malawi' },
    { name: 'Bishop Mackenzie International School, Lilongwe', state: 'Central, Malawi' },
    { name: 'Likuni Secondary School, Lilongwe', state: 'Central, Malawi' },
    { name: 'Marymount Secondary School, Blantyre', state: 'Southern, Malawi' },
  ],

  'Burundi': [
    { name: 'Ecole Belge de Bujumbura', state: 'Bujumbura, Burundi' },
    { name: 'Lyc\u00e9e Fran\u00e7ais de Bujumbura', state: 'Bujumbura, Burundi' },
    { name: 'International School of Bujumbura', state: 'Bujumbura, Burundi' },
    { name: 'Coll\u00e8ge Saint Esprit, Bujumbura', state: 'Bujumbura, Burundi' },
  ],

  'Eritrea': [
    { name: 'Eritrean Community Based School, Asmara', state: 'Maekel, Eritrea' },
    { name: 'Asmara International Community School', state: 'Maekel, Eritrea' },
    { name: 'Lyc\u00e9e Fran\u00e7ais d\'Asmara', state: 'Maekel, Eritrea' },
  ],

  'Eswatini': [
    { name: 'St. Mark\'s High School, Mbabane', state: 'Hhohho, Eswatini' },
    { name: 'Waterford Kamhlaba United World College, Mbabane', state: 'Hhohho, Eswatini' },
    { name: 'Salesian High School, Manzini', state: 'Manzini, Eswatini' },
  ],

  'Lesotho': [
    { name: 'Masitise High School, Maseru', state: 'Maseru, Lesotho' },
    { name: 'Machabeng International School, Maseru', state: 'Maseru, Lesotho' },
    { name: 'Lerotholi Polytechnic Secondary School, Maseru', state: 'Maseru, Lesotho' },
    { name: 'Basotho High School, Maseru', state: 'Maseru, Lesotho' },
  ],

  'Mauritania': [
    { name: 'Lyc\u00e9e Fran\u00e7ais de Nouakchott', state: 'Nouakchott, Mauritania' },
    { name: 'Coll\u00e8ge d\'Enseignement G\u00e9n\u00e9ral, Nouakchott', state: 'Nouakchott, Mauritania' },
    { name: 'American International School of Nouakchott', state: 'Nouakchott, Mauritania' },
  ],

  'The Gambia': [
    { name: 'St. Augustine\'s High School, Banjul', state: 'Banjul, The Gambia' },
    { name: 'Gambia Senior Secondary School, Banjul', state: 'Banjul, The Gambia' },
    { name: 'Banjul American International School', state: 'Banjul, The Gambia' },
    { name: 'St. Joseph\'s High School, Banjul', state: 'Banjul, The Gambia' },
    { name: 'Marina International School, Banjul', state: 'Banjul, The Gambia' },
  ],

  'Guinea-Bissau': [
    { name: 'Lyc\u00e9e Fran\u00e7ais de Bissau', state: 'Bissau, Guinea-Bissau' },
    { name: 'Escola Portuguesa de Bissau', state: 'Bissau, Guinea-Bissau' },
    { name: 'Lyc\u00e9e National de Bissau', state: 'Bissau, Guinea-Bissau' },
  ],

  'Central African Republic': [
    { name: 'Lyc\u00e9e Fran\u00e7ais Charles de Gaulle, Bangui', state: 'Bangui, CAR' },
    { name: 'International School of Bangui', state: 'Bangui, CAR' },
    { name: 'Lyc\u00e9e National de Bangui', state: 'Bangui, CAR' },
  ],

  'Equatorial Guinea': [
    { name: 'Colegio Nacional Enrique Nv\u00f3 Okenve, Malabo', state: 'Bioko Norte, Equatorial Guinea' },
    { name: 'International School of Malabo', state: 'Bioko Norte, Equatorial Guinea' },
    { name: 'American School of Malabo', state: 'Bioko Norte, Equatorial Guinea' },
  ],

  'Djibouti': [
    { name: 'Lyc\u00e9e Fran\u00e7ais de Djibouti', state: 'Djibouti City, Djibouti' },
    { name: 'Djibouti International School', state: 'Djibouti City, Djibouti' },
    { name: 'Coll\u00e8ge d\'Enseignement G\u00e9n\u00e9ral, Djibouti', state: 'Djibouti City, Djibouti' },
  ],

  'Seychelles': [
    { name: 'Seychelles College, Victoria', state: 'Mah\u00e9, Seychelles' },
    { name: 'International School Seychelles, Victoria', state: 'Mah\u00e9, Seychelles' },
    { name: 'Mont Fleuri Secondary School, Victoria', state: 'Mah\u00e9, Seychelles' },
  ],

  'Comoros': [
    { name: 'Lyc\u00e9e Fran\u00e7ais des Comores, Moroni', state: 'Grande Comore, Comoros' },
    { name: 'Lyc\u00e9e de Moroni', state: 'Grande Comore, Comoros' },
    { name: 'Coll\u00e8ge Said Mohamed Cheikh, Moroni', state: 'Grande Comore, Comoros' },
  ],

  'Cape Verde': [
    { name: 'Lyc\u00e9e Ludgero Lima, Mindelo', state: 'S\u00e3o Vicente, Cape Verde' },
    { name: 'International School of Cape Verde, Praia', state: 'Santiago, Cape Verde' },
    { name: 'Escola Portuguesa de Cabo Verde, Praia', state: 'Santiago, Cape Verde' },
  ],

  'S\u00e3o Tom\u00e9 and Pr\u00edncipe': [
    { name: 'Lyc\u00e9e National de S\u00e3o Tom\u00e9', state: '\u00c1gua Grande, S\u00e3o Tom\u00e9 and Pr\u00edncipe' },
    { name: 'Escola Portuguesa de S\u00e3o Tom\u00e9', state: '\u00c1gua Grande, S\u00e3o Tom\u00e9 and Pr\u00edncipe' },
    { name: 'Col\u00e9gio de S\u00e3o Tom\u00e9', state: '\u00c1gua Grande, S\u00e3o Tom\u00e9 and Pr\u00edncipe' },
  ],
}

function getAllSecondarySchools(country) {
  const all = []
  for (const [key, list] of Object.entries(schoolsByCountry)) {
    if (country && key !== country) continue
    for (const entry of list) {
      all.push({ name: entry.name, country: key, level: 'Secondary', state: entry.state })
    }
  }
  if (!country || country === 'Nigeria') {
    for (const entry of waecNigeria.nigeria) {
      all.push({ name: entry.name, country: 'Nigeria', level: 'Secondary', state: entry.state })
    }
  }
  return all
}

module.exports = { schoolsByCountry, getAllSecondarySchools }
