const mongoose = require('mongoose')

const userSchema = new mongoose.Schema({
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    username: { type: String, unique: true, sparse: true },
    phone: { type: String },
    password: { type: String },
    googleId: { type: String },
    level: { type: String, enum: ['JSS', 'SSS', 'Secondary', 'University'] },
    school: { type: String },
    faculty: { type: String },
    department: { type: String },
    state: { type: String },
    course: { type: String },
    interests: [{ type: String }],
    badges: [{ type: String }],
    badgeSubscriptions: [{ id: String, purchasedAt: Date, expiresAt: Date }],
    coins: { type: Number, default: 50 },
    lifetimeCoins: { type: Number, default: 50 },
    streak: { type: Number, default: 0 },
    lastPostDate: { type: Date },
    badge: { type: String, default: 'Beginner' },
    activatedFeatures: [{ type: String, enum: ['badge', 'transfer', 'community'] }],
    weeklyEngagementCoins: { type: Number, default: 0 },
    lastWeeklyPayout: { type: Date },
    isVerified: { type: Boolean, default: false },
    isAdmin: { type: Boolean, default: false },
    resetToken: { type: String },
    resetTokenExpiry: { type: Date },
    twoFactorEnabled: { type: Boolean, default: false },
    referralCode: { type: String, unique: true, sparse: true },
    referredBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    followers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    following: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    lastActive: { type: Date },
    botUsage: { date: String, count: { type: Number, default: 0 } },
}, { timestamps: true })

module.exports = mongoose.models.User || mongoose.model('User', userSchema)